apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-db
  name: my-db
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: my-db
  template:
    metadata:
      labels:
        app: my-db
    spec:
      hostname: my-db
      containers:
      - env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: database
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: user
        image: postgres:13.2
        imagePullPolicy: IfNotPresent
        name: my-db
        ports:
        - containerPort: 5432
        resources: {}
      restartPolicy: Always
status: {}
